### ISSUE TITLE
extended form

### ISSUE THREAD

**Issue by Level8Broccoli** [gilde-der-nacht/website#12]
form for game master, staff/helper, player etc.
similar issues #5 and #1

**Comment by Level8Broccoli** [comment]
Possible 3rd party solutions 

- Google Forms
- https://zapier.com/
- https://mailchimp.com/
- https://formspree.io/
- https://formkeep.com/
- http://parseplatform.org

**Comment by thomasstauffer666** [comment]
Google Forms: Form needs to be created first with their Form Builder an then field names need to extracted manually
FormSpree: Only 50 submissions per month
FormKeep: Only 50 submissions per month

**Comment by thomasstauffer666** [comment]
mailthis.to: theoretically fine, but doesn't seem to work anymore
formbucket.com: only 14 days trial

**Comment by Level8Broccoli** [comment]
@thomasstauffer666 can we close this for now?
