### ISSUE TITLE
markdown identation needs 4 spaces

### ISSUE THREAD

**Issue by thomasstauffer666** [gilde-der-nacht/website#17]
this is a well known problem

https://discourse.gohugo.io/t/markdown-unordered-list-parsing-issue/17728/2

https://github.com/russross/blackfriday/issues/329

should we try to fix this? (may take a long time until it arrives in Hugo)

**Comment by Level8Broccoli** [comment]
A fix from our side would be to just use 4 spaces each time?

**Comment by thomasstauffer666** [comment]
yes

**Comment by thomasstauffer666** [comment]
not fixed, but closed, if someone thinks it's important, please reopen
