### ISSUE TITLE
feedback rollenspieltage.ch v1.0

### ISSUE THREAD

**Issue by Level8Broccoli** [gilde-der-nacht/website#27]
- [x] after sending form, you are redirectet to https://gildedernacht.ch/contact/ but correct would be http://rollenspieltage.ch/contact/
- [x] footer on mobile doesn’t work: Facebook logo is overflowing, social logos hover effect renders underline
- [x] manual line-break in headline doesn’t look good on mobile: remove manual line-break
- [x] table (opening hours, startpage) looks weird on mobile
- [x] all relative links point to gildedernacht.ch/…

**Comment by thomasstauffer666** [comment]
1. and 5. -> baseURL was wrong

**Comment by Level8Broccoli** [comment]
Feedback Andrea

> Hallo Oli, du hast zum Feedback zur Website Rollenspieltage aufgerufen. Ich (als Grafikerin) kann hier höchstens zur Textgestaltung allg. etwas sagen. Die Schriftwahl finde ich sehr gelungen. Auch die Farbgebung und das Logo sind toll! Was für mich nicht ganz klar ist, ist die  Hierarchie der Navigation und die Definition resp. Gewichtung der Textsorten auf der Startseite. z.B. hebt sich das Datum der Veranstaltung kaum vom Lauftext ab. Auch der Text «Phase» und der Link: «Neu hier» gehört meiner Meinung nach nicht unbedingt in den Lauftext. Evtl. könnte man auch «Phase» noch weiter erläutern (welche Phasen gibt es, was ist erledigt, was kommt noch -> Zeitstrahl o.ä.). Der Lauftext erscheint mir allg. auch etwas gross. Dadurch wirkt das ganze auch etwas laut. Ich weiss nicht, ob ich mich verständlich ausgedrückt habe und ob dir das überhaupt weiterhilft. Vielleicht ist das aber auch nur eine subjektive Empfindung und ist von deinem Konzept her so gewollt. LG Andrea
> [Mobile:] Schwierige Frage. Die Grösse ist angenehm zu lesen, aber irgendwie hat es mir zu wenig Zeichen auf einer Zeile. Aber ich denke das ist ein Detail und die Leserlichkeit leidet kaum, da die Abschnitte kurz gehalten sind (was ich super finde).

**Comment by Level8Broccoli** [comment]
Feedback Daniel
> "Links" fehlen im Englischen. Ist es Absicht weil meistens nur deutsche Links sind?
> Auch wenn der Status: Spielleiter-Suche ist, wäre eine Seite für die Spielrunden schön (halt noch leer solange kein Spielleiter vorhanden ist)

**Comment by Level8Broccoli** [comment]
Feedback Kevin

> - Die Spielleiteranmeldung ist etwas zu versteckt finde ich. Es steht zwar oben man sucht Spielleiter, jedoch muss man relativ lange Scrollen, bis man sich als Spielleiter anmelden kann. Vor allem kommen zuerst mal zwei Absätze Infos zu Spielleiter, bevor der Link zur Anmeldung kommt. Die Anmeldung sollten meiner Meinung nach zusätzlich ganz oben nochmals erwähnt sein. So dass man direkt auf der Seite sieht: Wir suchen Spielleiter hier Anmelden. Evtl. auch als zusätzlichen Link zum Kontaktformular. Viele werden ansonsten die Anmeldung evtl. übersehen.
> - Bei der Adresse noch erwähnen, dass es genug Parkplätze in der Nähe hat(Parkhaus). Leute mit dem Auto interessieren sich meistens vor allem dafür. Also gibt es Parkplätze die genug lange offen sind.
> - Ich weiss dass die Räume und auch die Shirts Rot sind am Rollenspieltag, jedoch gilt Rot als aggressive Farbe und ich finde man sollte auf der Seite dies nach Möglichkeit vermeiden. Wurde mir zumindest mal beigebracht :)
> - Auf dem Smartphone nimmt das Menu zuviel Platz ein. Evtl. sollte man das als Dropdown machen. Siehe Screenshoot.
> - Wir haben meines Wissens nach am Rollenspieltag nicht gefragt ob wir die Fotos verwenden dürfen. Die Leute auf den Bildern könnten sich evtl. daran stören, dass Fotos ungefragt von Ihnen im Internet verfügbar sind.
> - Die Seite trifft jetzt nicht unbedingt meinen Geschmack. Weisser Hintergrund mit schwarzem Text wirkt auf mich immer etwas zu schlicht. Aber ist nur mein Geschmack :wink:

**Comment by Level8Broccoli** [comment]
- [ ] Program page
- [ ] Mention parking spaces
- [ ] Links page translation (en)

-> #30

**Comment by Level8Broccoli** [comment]
positions inside container are not correctly justified

![Bildschirmfoto 2019-06-11 um 11 07 31](https://user-images.githubusercontent.com/7040739/59259038-52b30800-8c39-11e9-8529-a12e30c1b714.png)

![Bildschirmfoto 2019-06-11 um 11 07 42](https://user-images.githubusercontent.com/7040739/59259037-521a7180-8c39-11e9-90b3-507353a8bc1c.png)

**Comment by Level8Broccoli** [comment]
Kevin

> Betreffend Design, finde ich ein schlichtes Design ansprechend, muss ja nicht mit Bildern überladen sein. Ich finde das aktuelle Design jedoch einen zacken zu schlicht und dadurch wirkt es etwas unfertig.
> Bspw. könnte man ja die Schriftart ändern, verkleinern und den Abstand zwischen den Zeilen etwas verkleinern. Das würde schon viel verbessern.
> Betreffend Menuführug kann man die ganze Navigation auf dem Smartphone eigentlich ausblenden und nur einen Menubutton haben, der dann das Menu links einfügt. S.h. Metroboutique oder PKZ.
> Ebenfalls würde ich das Symbol oben entfernen/im Menu einbauen(Schwert & Stift) sowie Deutsch & Englisch ins Menu aufnehmen oder viel kleiner machen. Der weisse Block oben nimmt zu viel Platz ein.
> Heute läuft alles Mittels Teaser. Teaser ist modern. Darum wäre anstatt Bild & Text ein Teaser mit Text evtl. ansprechender. (Beim Titel)
> Das Design ist Text, Bild, Text, Bild. Man könnte Links ein Bild und rechts den Text haben und dann zwischen den beiden abwechseln. Bspw. wie bei https://www.pkz.ch/de/news. Dann kann man die Schriftgrösse auch so lassen. Jedoch wäre eine andere Schriftart trotzdem ansprechender. So hat man nicht einen Textblock und Links/Rechts nur riesige weisse Balken. Die Bilder sind recht gut gewählt. Bei Spielleiter steht wirklich ein Spielleiter im Zentrum vom Bild etc. Betreffend rechtlichem Aspekt kann man sich auch mal treffen und ein Fotoshooting machen, so dass wir keine rechtlichen Probleme haben.
> Dann könnte man den Bereich: Aktuelle Phase, sowie die Daten etwas ausarbeiten. Bspw. Tabellarisch darstellen. Vielleicht sogar die Möglichkeit geben mit Javascript zukünftige Phasen auszuwählen mit Pfleilen Links/Rechts oder sich die Termine im Kalender eintragen zu lassen. Die Daten könnte man auch etwas in Kalenderform darstellen

> ich finde bspw. den PKZ Teaser sehr gelungen. Darf gerne den ganzen Bildschirm einnehmen und die Übergänge sind fliesend und nicht aggressiv. Jedoch würde ich eher weiche Bilder nehmen und nicht so ein rotes Sale wie aktuell.
> da kann man auch mit unterschiedlichen Bildern arbeiten. Bspw zurzeit mit Spielleitersuche und dann nimmt man folgendes Bild dazu

**Comment by Level8Broccoli** [comment]
Content updates -> #30 
Problems with theme -> #31
Theme optimization for mobile -> #32
